.TH "node" 3 "Tue Sep 27 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtitle\fP"
.br
.ti -1c
.RI "string \fBauthor\fP"
.br
.ti -1c
.RI "string \fBdate\fP"
.br
.ti -1c
.RI "string \fBcontent\fP"
.br
.ti -1c
.RI "string \fBlink\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string node::author"

.SS "string node::content"

.SS "string node::date"

.SS "string node::link"

.SS "string node::title"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
