.TH "searcheng.cpp" 3 "Tue Sep 27 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
searcheng.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <bits/stdc++\&.h>\fP
.br
\fC#include 'dictionary\&.cpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
