.TH "stemmer" 3 "Tue Sep 27 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stemmer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBb\fP"
.br
.ti -1c
.RI "int \fBk\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* stemmer::b"

.SS "int stemmer::j"

.SS "int stemmer::k"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
